### ISSUE TITLE
Custom image and inter task communication

### ISSUE THREAD

**Issue by lazargugleta** [argoproj-labs/hera-workflows#395] opened 2022-12-22 19:57 UTC
I am facing the issue of not being able to load pickle files from the task that previously saved them.
My assumption is it has to do something with the custom image because the [example](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/artifact_with_fanout.py) by hera runs without any problems.
Any ideas?
Here is my code:
```python
from hera import Artifact, ImagePullPolicy
from hera.task import Task
from hera.workflow import Workflow
from hera.workflow_service import WorkflowService


def task_cleaned_data_housing(data_url):
    import pathlib
    import pickle

    import data_housing_pipeline_module

    data_url = str(data_url)

    training_data = data_housing_pipeline_module.get_cleaned_data_housing(
        data_url
    )

    if not pathlib.Path("/tmp").joinpath("data_housing_pipeline").exists():
        pathlib.Path("/tmp").joinpath("data_housing_pipeline").mkdir()
    pickle.dump(
        training_data,
        open("/tmp/data_housing_pipeline/variable_training_data.pickle", "wb"),
    )


def task_linear_model_housing():
    import pathlib
    import pickle

    import data_housing_pipeline_module

    training_data = pickle.load(
        open("/tmp/data_housing_pipeline/variable_training_data.pickle", "rb")
    )

    linear_model = data_housing_pipeline_module.get_linear_model_housing(
        training_data
    )

    if not pathlib.Path("/tmp").joinpath("data_housing_pipeline").exists():
        pathlib.Path("/tmp").joinpath("data_housing_pipeline").mkdir()
    pickle.dump(
        linear_model,
        open("/tmp/data_housing_pipeline/variable_linear_model.pickle", "wb"),
    )


ws = WorkflowService(
    host="https://localhost:2746",
    verify_ssl=False,
    token="None",
    namespace="argo",
)

with Workflow("data-housing-pipeline", service=ws) as w:

    cleaned_data_housing = Task(
        "cleaned-data-housing",
        task_cleaned_data_housing,
        [
            {
                "data_url": "https://raw.githubusercontent.com/LineaLabs/lineapy/main/examples/use_cases/predict_house_price/data/ames_train_cleaned.csv",
            }
        ],
        image="argo_pipeline:latest",
        image_pull_policy=ImagePullPolicy.Never,
        outputs=[
            Artifact(
                "training_data",
                "/tmp/data_housing_pipeline/variable_training_data.pickle",
            ),
        ],
    )

    linear_model_housing = Task(
        "linear-model-housing",
        task_linear_model_housing,
        image="argo_pipeline:latest",
        image_pull_policy=ImagePullPolicy.Never,
        inputs=[cleaned_data_housing.get_artifact("training_data")],
        outputs=[
            Artifact(
                "linear_model",
                "/tmp/data_housing_pipeline/variable_linear_model.pickle",
            ),
        ],
    )

    cleaned_data_housing >> linear_model_housing

w.create()
``` 

The message I get is:
`Unable to resolve: "tasks.cleaned-data-housing.outputs.artifacts.training_data"`
![image](https://user-images.githubusercontent.com/37106022/209215939-77a7bcdc-35eb-4f49-9eb8-67a6648257db.png)

**Comment by flaviuvadan** [comment] 2022-12-28 22:32
Thank you for the question @lazargugleta! What does the Argo UI show in the inputs/outputs field of the `cleaned-data-housing` task?

**Comment by lazargugleta** [comment] 2022-12-28 23:08
Thanks for responding @flaviuvadan! 
Here is how inputs/outputs field of the `cleaned-data-housing` task looks like:

![image](https://user-images.githubusercontent.com/37106022/209883331-6a52d2db-ae2a-4855-ae78-fa570cbba247.png)

**Comment by flaviuvadan** [comment] 2023-01-04 01:42
The `outputs` field looks ok from my perspective.. how big is the `variable_training_data.pickle` file? Is it 100Mb+? I wonder if there's some size limitation for `/tmp` on the machine. If you mount a separate disk to `/mnt` and save the file there, can you replicate the behavior?

**Comment by lazargugleta** [comment] 2023-01-04 08:07
When I extract the file, it is 112.8 kB so pretty small.
Here is how the dockerfile looks like to get the image:
```
FROM python:3.10

RUN mkdir /tmp/installers
WORKDIR /tmp/installers

# Copy all the requirements to run current DAG
COPY ./data_housing_pipeline_requirements.txt ./

# Install required libs
RUN pip install -r ./data_housing_pipeline_requirements.txt

WORKDIR /opt/argo/dags

# Install git and argo
RUN apt update
RUN apt install -y git
RUN pip install argo-workflows
RUN pip install hera-workflows

COPY ./data_housing_pipeline_module.py ./
COPY ./data_housing_pipeline_dag.py ./

ENTRYPOINT [ "argo", "repro", "run_all_sessions"]
```

I also just tried the `/mnt' instead of '/tmp' but the behavior is the same.


![image](https://user-images.githubusercontent.com/37106022/210510665-2b9db277-119c-48c1-937f-8521fe820570.png)

**Comment by Trollgeir** [comment] 2023-01-10 18:31
I believe the problem is related to the fact that we're using a `with_params` argument. In essence, Argo doesn't know which of the items (even though it's just 1) you're asking for the artifact. See discussion [here](https://github.com/argoproj/argo-workflows/issues/1625)

I think you can circumvent this issue by explicitly setting the input parameters to something like:

```python
  cleaned_data_housing = Task(
        "cleaned-data-housing",
        task_cleaned_data_housing,
        inputs=[Parameter("data_url", "https://raw.githubusercontent.com/LineaLabs/lineapy/main/examples/use_cases/predict_house_price/data/ames_train_cleaned.csv")],
        image="argo_pipeline:latest",
        ...
      
```

**Comment by flaviuvadan** [comment] 2023-03-21 02:13
Closing this for now but feel free to reopen this if it requires further discussion @lazargugleta! :)

**Closed by flaviuvadan** 2023-03-21 02:13 UTC
Labels: type:question
