### ISSUE TITLE
EnvSpec bug?

### ISSUE THREAD

**Issue by KukumavMozolo** [argoproj-labs/hera-workflows#62] opened 2022-01-19 11:49 UTC
Not sure if intended but setting environment variables via EnvSpec leaves unwanted quotation marks in the string when resolved in python script as shown below.

Steps to reproduce: Execute the below task and see that it prints false, while it should be true

`def test_env_spec():

    ressource = Resources(
            min_cpu=1,
            max_cpu=2,
            min_mem="2Gi",
            max_mem="4Gi"
    )
    envs = [
        EnvSpec(
                name="ENV_STRING",
                value='test'
        ),
    ]
    task = Task(
            'test',
            lambda: _,
            None,
            image='python:3.7',
            command=[
                "python",
                "-c",
                "import os; print(os.environ['ENV_STRING']);print(os.environ['ENV_STRING']=='test')",
            ],
            resources=ressource,
            env_specs=envs
    )
    return task

**Comment by KukumavMozolo** [comment] 2022-01-19 12:17
probably caused by json.dumps(self.value) in
`   def argo_spec(self) -> V1EnvVar:

        """Constructs and returns the Argo environment specification"""
        value = self.value.json() if isinstance(self.value, BaseModel) else json.dumps(self.value)
        return V1EnvVar(name=self.name, value=value)
`

**Comment by flaviuvadan** [comment] 2022-01-19 15:04
Hey @KukumavMozolo! Thanks for bringing this up 🙂  This is a great catch, actually. Would you like to submit a PR with a PATCH to fix this?

**Comment by KukumavMozolo** [comment] 2022-01-19 16:17
Yes please

**Comment by flaviuvadan** [comment] 2022-01-20 13:12
I've been thinking more about this issue. I think the original design was intended to be (1) consistent with the specifications of the [EnvVar](https://argoproj.github.io/argo-workflows/fields/#envvar) from Argo Workflow, which need a `string` for the `value `field` and (2) offer users a consistent way to load all values via `json.loads`. I think adding an exception for Python strings exclusively will violate the aforementioned second point. I think it's overall safer to encourage the use of `json.loads(os.environ['VAR'])` rather than encourage it _sometimes_, conditioned on the internals of Hera JSON serialization. For instance, if `EnvVar` sets the `value` field to just the string value that is passed in, then users will not have to use `json.loads`. However, a `json.loads` will be required for everything else. I think a consistent pattern for loading of env vars via `json.loads` is generally more accessible. Therefore, I think we should not go forward with merging #63. What do you think @KukumavMozolo? I am very aware that this goes against the point I made [here](https://github.com/argoproj-labs/hera-workflows/issues/62#issuecomment-1016556926) but I had to do more thinking on my own about whether we should add the string exception.

In light of this, I think the test script you shared above can be:
```python
def t():
    import os, json
    print(json.loads(os.environ['ENV_STRING']) == 'test')

task = Task('test', t, env_specs=[EnvSpec(name="ENV_STRING", value='test')])
```

I tested a more extended script with integers, strings, and dictionaries to test out the current usage. This is the script: 
```python
def hello():
    import os, json

    s1 = json.loads(os.environ.get('s1'))
    s2 = json.loads(os.environ.get('s2'))
    s3 = json.loads(os.environ.get('s3'))
    print(s1, s1 == 1)
    print(s2, s2 == 'hello')
    print(s3, s3 == {'a': 1, 'b': 'hello'})

t = Task('t', hello, env_specs=[
    EnvSpec(name='s1', value=1),
    EnvSpec(name='s2', value='hello'),
    EnvSpec(name='s3', value={'a': 1, 'b': 'hello'})
])
```

After completion the output was:
```text
1 True
hello True
{'a': 1, 'b': 'hello'} True
```

One thing Hera could do for users is to deserialize the values into the environment variables themselves. The same way `json.loads` is injected for parameters, the same way another `json.loads` can be injected into the script to deserialize environment variables when function payloads are used. Any thoughts? 🙂

**Comment by KukumavMozolo** [comment] 2022-01-20 13:22
That would not work with env variables outside of python (which is actually my use case). Or is there another way?

**Comment by flaviuvadan** [comment] 2022-01-20 14:04
> That would not work with env variables that are used in the container but outside of python (which is actually my use case).

Oh, I see... My apologies. I did not realize the use case is to access environment variables _outside_ of running `python`. Ok, I feel like I have a more complete picture now. I will have to think about this for the case of other types, such as integers and floats. Do you think the cases changes? Or, is it, perhaps, pretty standard to store these as strings in env variables? I, for one, have seen both... some projects use `"1"` as a boolean variable, for instance, and some use `1` or `True`, of course.

**Comment by KukumavMozolo** [comment] 2022-01-20 15:05
Good question, when comparing to couler-generated *.yml file, they seem to put only the string without any ' or " signs.

**Comment by flaviuvadan** [comment] 2022-01-24 14:30
Thank you for the discussion @KukumavMozolo 🙂 I looked through the [POSIX definition of an environment variable](https://pubs.opengroup.org/onlinepubs/9699919799/). I now think that the PR you have actually brings Hera closer to setting environment values closer to the way they are actually defined. In this case, a `string` is literally a `string` and can be used as one. In the case of non-string values, that's when a `json.dumps` is used to create the literal `string` required to satisfy the definition. The context/use case _around_ the `string` can dictate other things, such as whether it should be turned into an integer, or a Pydantic `BaseModel`, for instance. I will approve the PR you have up! Going to close this issue. Again, thank you very much for the informative discussion 🙂

**Closed by flaviuvadan** 2022-01-24 14:30 UTC
